---
- name: Load custom PHP settings
  template: src=custom.ini.j2 dest=/etc/php/{{ php_version }}/mods-available/custom.ini owner=root group=root mode=0644

- name: Set custom links for cli
  file: src=/etc/php/{{ php_version }}/mods-available/custom.ini dest=/etc/php/{{ php_version }}/cli/conf.d/30-custom.ini state=link

- name: Set custom links for fpm
  file: src=/etc/php/{{ php_version }}/mods-available/custom.ini dest=/etc/php/{{ php_version }}/fpm/conf.d/30-custom.ini state=link

- name: Enable FPM Pool for www
  template: src=fpm_www.j2 dest=/etc/php/{{ php_version }}/fpm/pool.d/www.conf owner=root group=root mode=0664

- name: Restart php-fpm service
  become: true
  become_user: root
  service: name=php{{ php_version }}-fpm state=restarted
